language: node_js
node_js:
  - "8"
  - "10"
  - "12"
services:
  - xvfb
addons:
  firefox: latest
before_script:
  - "export DISPLAY=:99.0"
script:
  - npm run lint
  - npm test
  - npm run test:browserify -- ci -l Firefox
  - npm run test:webpack -- ci -l Firefox
